version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv dev
            . dev/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run Server
          command: |
            . dev/bin/activate
            gunicorn run:app --bind=127.0.0.1:5000 --pid=gunicorn.txt --daemon
          background: true

      - run:
          name: run tests
          command: |
            . dev/bin/activate
            cd server/
            sleep 3
            python -m unittest tests/test_models.py
            python -m unittest tests/test_back.py